development:
  adapter: mysql2
  host: localhost
  username: root
  password: password
  database: db_development

test:
  adapter: mysql2
  host: localhost
  username: root
  password: password
  database: db_test

production:
  adapter: mysql2
  host: localhost
  username: root
  password: password
  database: db_production
